name: Deploy to Github Pages

on:
  push:
    branches:
      - release
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  setup-dep:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set page url
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          USER_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)

          if [ $REPO_NAME = "$USER_NAME.github.io" ]; then
            PAGE_URL="https://$USER_NAME.github.io/"
          else
            PAGE_URL="https://$USER_NAME.github.io/$REPO_NAME/"
          fi

          echo "PAGE_URL=$PAGE_URL" >> $GITHUB_ENV

  build-pages:
    runs-on: ubuntu-latest
    needs: setup-dep
    steps:
      - name: Build Pages
        run: pnpm page:all

  build-beta:
    runs-on: ubuntu-latest
    needs: setup-dep
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Build
        run: pnpm release --configBaseURL $PAGE_URL --configBeta

  build-release:
    runs-on: ubuntu-latest
    needs: setup-dep
    steps:
      - name: Checkout release
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Build
        run: pnpm release --configBaseURL $PAGE_URL

  deploy:
    runs-on: ubuntu-latest
    needs: [build-pages, build-beta, build-release]
    steps:
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ./public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
